# Generated by Django 4.1.7 on 2023-05-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='imagenes/', verbose_name='Imagen')),
                ('descriprion', models.TextField(null=True, verbose_name='Descripción')),
            ],
        ),
    ]
