# Generated by Django 4.1.4 on 2023-05-16 14:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descriprion',
        ),
        migrations.AddField(
            model_name='producto',
            name='agregado',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Agregado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='lugar',
            field=models.CharField(max_length=100, null=True, verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.IntegerField(null=True, verbose_name='Precio_compra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.IntegerField(null=True, verbose_name='Precio_venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
